#!/bin/bash
#
# ==================================================

# Initializing Var
export DEBIAN_FRONTEND=noninteractive
OS=`uname -m`;
MYIP=$(wget -qO- ipv4.icanhazip.com);
MYIP2="s/xxxxxxxxx/$MYIP/g";

# Details of VenomVPN
country=PH
state=Manila
locality=Manila
organization=VenomVPN
organizationalunit=VenomVPN
commonname=VenomVPN
email=venomvpn@gmail.com

# Intial
apt-get update;apt-get -y install wget
sh -c 'echo "deb http://download.webmin.com/download/repository sarge contrib" > /etc/apt/sources.list.d/webmin.list'
wget -qO - http://www.webmin.com/jcameron-key.asc | apt-key add -

# update
apt-get update


# remove old squid & openvpn
cd
apt-get purge openvpn -y && apt-get purge squid3 -y
rm -rfv /etc/openvpn
rm -rfv /etc/squid3

# install squid3
cd
apt-get -y install squid3
wget -O /etc/squid3/squid.conf "https://raw.githubusercontent.com/rlguia/debian-8.7-openvpn/master/squid3.conf"
sed -i $MYIP2 /etc/squid3/squid.conf;
service squid3 restart

# install openvpn
cd
wget https://git.io/vpn -O openvpn-install.sh && bash openvpn-install.sh
wget -0 /etc/openvpn.zip
cd /etc/openvpn/
unzip openvpn.zip
/etc/init.d/openvpn restart

# install essential package
cd
apt-get -y install nano iptables dnsutils screen whois ngrep unzip unrar


# install webmin
cd
apt-get install -y perl libnet-ssleay-perl openssl libauthen-pam-perl libpam-runtime libio-pty-perl apt-show-versions python
apt-get -y install apt-transport-https webmin
sed -i 's/ssl=1/ssl=0/g' /etc/webmin/miniserv.conf
/etc/init.d/webmin restart

# go to root
cd

# disable ipv6
echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6
sed -i '$ i\echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6' /etc/rc.local

# install curl
apt-get -y install curl;

# set time GMT +7
ln -fs /usr/share/zoneinfo/Asia/Manila /etc/localtime

# set locale
sed -i 's/AcceptEnv/#AcceptEnv/g' /etc/ssh/sshd_config
service ssh restart

# set repo
wget -O /etc/apt/sources.list "https://raw.githubusercontent.com/rlguia/debian-8.7-openvpn/master/sources.list.debian7"
wget "http://www.dotdeb.org/dotdeb.gpg"
cat dotdeb.gpg | apt-key add -;rm dotdeb.gpg

# install webserver
apt-get -y install nginx


echo "clear" >> .bashrc
echo 'echo -e ""' >> .bashrc
echo 'echo -e ""' >> .bashrc
echo 'echo -e ""' >> .bashrc
echo 'echo -e "Welcome to VenomVPN $HOSTNAME"' >> .bashrc
echo 'echo -e "For Commands, input menu"' >> .bashrc
echo 'echo -e ""' >> .bashrc
echo 'echo -e ""' >> .bashrc
echo 'echo -e ""' >> .bashrc
echo 'echo -e ""' >> .bashrc

# install webserver
cd
rm /etc/nginx/sites-enabled/default
rm /etc/nginx/sites-available/default
wget -O /etc/nginx/nginx.conf "http://vira.cf/nginx.conf"
mkdir -p /home/vps/public_html
echo "<pre>VenomVPN</pre>" > /home/vps/public_html/index.html
echo "<pre>VenomVPN - https://www.facebook.com/groups/venomvpn-official</pre>" > /home/vps/public_html/index.html
wget -O /etc/nginx/conf.d/vps.conf "https://raw.githubusercontent.com/rlguia/debian-8.7-openvpn/master/vps.conf"
service nginx restart




# setting port ssh
cd
sed -i 's/Port 22/Port 22/g' /etc/ssh/sshd_config
sed -i '/Port 22/a Port 444' /etc/ssh/sshd_config
service ssh restart




#END

# install fail2ban
apt-get -y install fail2ban;
service fail2ban restart

# install ddos deflate
cd
apt-get -y install dnsutils dsniff
wget https://raw.githubusercontent.com/rlguia/debian-8.7-openvpn/master/ddos-deflate-master.zip
unzip ddos-deflate-master.zip
cd ddos-deflate-master
./install.sh
rm -rf /root/ddos-deflate-master.zip

# banner
rm /etc/issue.net
wget -O /etc/issue.net "https://raw.githubusercontent.com/rlguia/debian-8.7-openvpn/master/issue.net"
sed -i 's@#Banner@Banner@g' /etc/ssh/sshd_config
service ssh restart

# download script
cd /usr/bin
wget -O menu "https://raw.githubusercontent.com/rlguia/debian-8.7-openvpn/master/menu.sh"
wget -O add "https://raw.githubusercontent.com/rlguia/debian-8.7-openvpn/master/usernew.sh"
wget -O trial "https://raw.githubusercontent.com/rlguia/debian-8.7-openvpn/master/trial.sh"
wget -O remove "https://raw.githubusercontent.com/rlguia/debian-8.7-openvpn/master/hapus.sh"
wget -O check "https://raw.githubusercontent.com/rlguia/debian-8.7-openvpn/master/user-login.sh"
wget -O member "https://raw.githubusercontent.com/rlguia/debian-8.7-openvpn/master/user-list.sh"
wget -O banner "https://raw.githubusercontent.com/rlguia/debian-8.7-openvpn/master/servermessage.sh"
wget -O restart "https://raw.githubusercontent.com/rlguia/debian-8.7-openvpn/master/resvis.sh"
wget -O speedtest "https://raw.githubusercontent.com/rlguia/debian-8.7-openvpn/master/speedtest_cli.py"
wget -O info "https://raw.githubusercontent.com/rlguia/debian-8.7-openvpn/master/info.sh"
wget -O about "https://raw.githubusercontent.com/rlguia/debian-8.7-openvpn/master/about.sh"

echo "0 0 * * * root /sbin/reboot" > /etc/cron.d/reboot

chmod +x menu
chmod +x add
chmod +x trial
chmod +x remove
chmod +x check
chmod +x member
chmod +x banner
chmod +x restart
chmod +x speedtest
chmod +x info
chmod +x about

# finishing
cd
chown -R www-data:www-data /home/vps/public_html
service nginx start
service cron restart
service ssh restart
service squid3 restart
/etc/init.d/webmin restart
rm -rf ~/.bash_history && history -c
echo "unset HISTFILE" >> /etc/profile

# install neofetch
echo "deb http://dl.bintray.com/dawidd6/neofetch jessie main" | tee -a /etc/apt/sources.list
curl "https://bintray.com/user/downloadSubjectPublicKey?username=bintray"| apt-key add -
apt-get update
apt-get install neofetch

echo "deb http://dl.bintray.com/dawidd6/neofetch jessie main" | tee -a /etc/apt/sources.list
curl "https://bintray.com/user/downloadSubjectPublicKey?username=bintray"| apt-key add -
apt-get update
apt-get install neofetch

# info
clear
echo "AutoScriptVPS Includes:" | tee log-install.txt
echo "===========================================" | tee -a log-install.txt
echo ""  | tee -a log-install.txt
echo "Service"  | tee -a log-install.txt
echo "-------"  | tee -a log-install.txt
echo "OpenSSH  : 22, 444"  | tee -a log-install.txt
echo "Dropbear : 80, 553"  | tee -a log-install.txt
echo "SSL      : 143"  | tee -a log-install.txt
echo "Squid3   : 8000, 8080 (limit to IP SSH)"  | tee -a log-install.txt
echo "OpenVPN  : TCP 1194 (client config : http://$MYIP:81/client.ovpn)"  | tee -a log-install.txt
echo "badvpn   : badvpn-udpgw port 7300"  | tee -a log-install.txt
echo "nginx    : 81"  | tee -a log-install.txt
echo ""  | tee -a log-install.txt
echo "Commands"  | tee -a log-install.txt
echo "------"  | tee -a log-install.txt
echo "menu       (Show Commands)"  | tee -a log-install.txt
echo "add        (Create User Account)"  | tee -a log-install.txt
echo "trial      (Create Trial Account)"  | tee -a log-install.txt
echo "remove     (Remove User Account)"  | tee -a log-install.txt
echo "check      (Check User Login)"  | tee -a log-install.txt
echo "member     (Check Member)"  | tee -a log-install.txt
echo "banner     (Configure Server Message)"  | tee -a log-install.txt
echo "restart    (Restart Service Dropbear, Webmin,"  | tee -a log-install.txt
echo "            Squid3, Openvpn and SSH)"  | tee -a log-install.txt
echo "reboot     (Reboot VPS)"  | tee -a log-install.txt
echo "speedtest  (Speedtest VPS)"  | tee -a log-install.txt
echo "info       (System Information)"  | tee -a log-install.txt
echo "about      (Debian AutoScript VPS Info)"  | tee -a log-install.txt
echo ""  | tee -a log-install.txt
echo "Other Features"  | tee -a log-install.txt
echo "----------"  | tee -a log-install.txt
echo "DDoS Deflate   : Anti-DDOS"  | tee -a log-install.txt
echo "Webmin         : http://$MYIP:10000/"  | tee -a log-install.txt
echo "Timezone       : Asia/Manila (GMT +7)"  | tee -a log-install.txt
echo "IPv6           : [off]"  | tee -a log-install.txt
echo ""  | tee -a log-install.txt
echo "--"  | tee -a log-install.txt
echo "--"  | tee -a log-install.txt
echo "--"  | tee -a log-install.txt
echo "VenomVPN"  | tee -a log-install.txt
echo ""  | tee -a log-install.txt
echo "Installation Logs --> /root/log-install.txt"  | tee -a log-install.txt
echo ""  | tee -a log-install.txt
echo "VPS Auto Reboot at 12 AM"  | tee -a log-install.txt
echo ""  | tee -a log-install.txt
echo "==========================================="  | tee -a log-install.txt
cd
rm -f /root/debian7.sh




