#!/bin/bash
#
#
# ==================================================

# Initializing Var
export DEBIAN_FRONTEND=noninteractive
OS=`uname -m`;
MYIP=$(wget -qO- ipv4.icanhazip.com);
MYIP2="s/xxxxxxxxx/$MYIP/g";

# Details of VenomVPN
country=PH
state=Manila
locality=Manila
organization=VenomVPN
organizationalunit=VenomVPN
commonname=VenomVPN
email=venomvpn@gmail.com

# set time GMT +7
ln -fs /usr/share/zoneinfo/Asia/Manila /etc/localtime

# set locale
sed -i 's/AcceptEnv/#AcceptEnv/g' /etc/ssh/sshd_config
service ssh restart

# Install Updates 
echo "Installing Updates"
cd
sh -c 'echo "deb http://download.webmin.com/download/repository sarge contrib" > /etc/apt/sources.list.d/webmin.list'
wget -qO - http://www.webmin.com/jcameron-key.asc | apt-key add -
clear
apt-get update -y && apt-get upgrade -y
apt-get -y install wget nano iptables dnsutils openvpn screen whois ngrep unzip unrar squid3 tcpkill nslookup curl nginx dropbear

wget "http://www.dotdeb.org/dotdeb.gpg"
cat dotdeb.gpg | apt-key add -;rm dotdeb.gpg


# install webmin
clear
echo "Installing Webmin"
cd
apt-get install -y perl libnet-ssleay-perl openssl libauthen-pam-perl libpam-runtime libio-pty-perl apt-show-versions python
apt-get -y install apt-transport-https webmin
sed -i 's/ssl=1/ssl=0/g' /etc/webmin/miniserv.conf
/etc/init.d/webmin restart


# disable ipv6
clear
echo "Disabling IPv6"
echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6
sed -i '$ i\echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6' /etc/rc.local





echo "clear" >> .bashrc
echo 'echo -e "==========================="' >> .bashrc
echo 'echo -e "Welcome to $HOSTNAME" server' >> .bashrc
echo 'echo -e "For Commands, input menu"' >> .bashrc
echo 'echo -e "==========================="' >> .bashrc




# install webserver
cd
clear
echo "Installing Nginx"
apt-get install nginx -y
rm /etc/nginx/sites-enabled/default
rm /etc/nginx/sites-available/default
wget -O /etc/nginx/nginx.conf "http://vira.cf/nginx.conf"
mkdir -p /home/vps/public_html
echo "<pre>VenomVPN</pre>" > /home/vps/public_html/index.html
wget -O /etc/nginx/conf.d/vps.conf "https://raw.githubusercontent.com/rlguia/debian-8.7-openvpn/master/vps.conf"
service nginx restart


# install openvpn
clear
echo "Install OpenVPN"
cd
apt-get install openvpn -y
cd /etc/openvpn/
mkdir /etc/openvpn/keys
cd /etc/openvpn/keys
wget -O /etc/openvpn/keys/ca.crt "https://github.com/rlguia/debian-8.7-openvpn/raw/master/ca.crt"
wget -O /etc/openvpn/keys/dh1024.pem "https://github.com/rlguia/debian-8.7-openvpn/raw/master/dh1024.pem"
wget -O /etc/openvpn/keys/server.crt "https://github.com/rlguia/debian-8.7-openvpn/raw/master/server.crt"
wget -O /etc/openvpn/keys/server.key "https://github.com/rlguia/debian-8.7-openvpn/raw/master/server.key"
cd /etc/openvpn
rm -rfv /etc/openvpn/server.conf
wget -O /etc/openvpn/server.conf "https://github.com/rlguia/debian-8.7-openvpn/raw/master/server.conf"
wget -O /etc/openvpn/openvpn-auth-pam.so "https://github.com/rlguia/debian-8.7-openvpn/raw/master/openvpn-auth-pam.so"
/etc/init.d/openvpn restart

sysctl -w net.ipv4.ip_forward=1
sed -i 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/g' /etc/sysctl.conf
iptables -t nat -I POSTROUTING -s 192.168.100.0/24 -o eth0 -j MASQUERADE
iptables-save > /etc/iptables_yg_baru_dibikin.conf
wget -O /etc/network/if-up.d/iptables "https://raw.githubusercontent.com/rlguia/debian-8.7-openvpn/master/iptables"
chmod +x /etc/network/if-up.d/iptables
/etc/init.d/openvpn restart



# openvpn configuration
clear
echo "Configuring OpenVPN"
cd /etc/openvpn/
wget -O /etc/openvpn/client.ovpn "https://raw.githubusercontent.com/rlguia/debian-8.7-openvpn/master/client-1194.conf"
sed -i $MYIP2 /etc/openvpn/client.ovpn;
cp client.ovpn /home/vps/public_html/

# install squid3
clear
echo "Installing Squid3"
cd
apt-get -y install squid3
wget -O /etc/squid3/squid.conf "https://raw.githubusercontent.com/rlguia/debian-8.7-openvpn/master/squid3.conf"
sed -i $MYIP2 /etc/squid3/squid.conf;
/etc/init.d/squid3 restart


# setting port ssh
clear
echo "Configuring SSH"
cd
sed -i 's/Port 22/Port 22/g' /etc/ssh/sshd_config
sed -i '/Port 22/a Port 444' /etc/ssh/sshd_config
service ssh restart



# install fail2ban
clear
echo "Installing Fail2Ban"
apt-get -y install fail2ban;
service fail2ban restart

# install ddos deflate
clear
echo "Installing Anti-DDOS"
cd
apt-get -y install dnsutils dsniff
wget https://raw.githubusercontent.com/rlguia/debian-8.7-openvpn/master/ddos-deflate-master.zip
unzip ddos-deflate-master.zip
cd ddos-deflate-master
./install.sh
rm -rf /root/ddos-deflate-master.zip

# banner
clear
echo "Finishing Setup"
rm /etc/issue.net
wget -O /etc/issue.net "https://raw.githubusercontent.com/rlguia/debian-8.7-openvpn/master/issue.net"
sed -i 's@#Banner@Banner@g' /etc/ssh/sshd_config
service ssh restart

# download script
clear
echo "Installing Scripts"
cd /usr/bin
wget -O menu "https://raw.githubusercontent.com/rlguia/debian-8.7-openvpn/master/menu.sh"
wget -O add "https://raw.githubusercontent.com/rlguia/debian-8.7-openvpn/master/usernew.sh"
wget -O trial "https://raw.githubusercontent.com/rlguia/debian-8.7-openvpn/master/trial.sh"
wget -O remove "https://raw.githubusercontent.com/rlguia/debian-8.7-openvpn/master/hapus.sh"
wget -O check "https://raw.githubusercontent.com/rlguia/debian-8.7-openvpn/master/user-login.sh"
wget -O member "https://raw.githubusercontent.com/rlguia/debian-8.7-openvpn/master/user-list.sh"
wget -O banner "https://raw.githubusercontent.com/rlguia/debian-8.7-openvpn/master/servermessage.sh"
wget -O restart "https://raw.githubusercontent.com/rlguia/debian-8.7-openvpn/master/resvis.sh"
wget -O speedtest "https://raw.githubusercontent.com/rlguia/debian-8.7-openvpn/master/speedtest_cli.py"
wget -O info "https://raw.githubusercontent.com/rlguia/debian-8.7-openvpn/master/info.sh"
wget -O about "https://raw.githubusercontent.com/rlguia/debian-8.7-openvpn/master/about.sh"

echo "0 0 * * * root /sbin/reboot" > /etc/cron.d/reboot

chmod +x menu
chmod +x add
chmod +x trial
chmod +x remove
chmod +x check
chmod +x member
chmod +x banner
chmod +x restart
chmod +x speedtest
chmod +x info
chmod +x about


cd
chown -R www-data:www-data /home/vps/public_html
service nginx start
service openvpn restart
service cron restart
service ssh restart
service squid3 restart
/etc/init.d/webmin restart
rm -rf ~/.bash_history && history -c
echo "unset HISTFILE" >> /etc/profile

# install neofetch
echo "deb http://dl.bintray.com/dawidd6/neofetch jessie main" | tee -a /etc/apt/sources.list
curl "https://bintray.com/user/downloadSubjectPublicKey?username=bintray"| apt-key add -
apt-get update
apt-get install neofetch

echo "deb http://dl.bintray.com/dawidd6/neofetch jessie main" | tee -a /etc/apt/sources.list
curl "https://bintray.com/user/downloadSubjectPublicKey?username=bintray"| apt-key add -
apt-get update
apt-get install neofetch

# info
clear
echo "===========================================" | tee -a log-install.txt
echo "Setup Finished!"  | tee -a log-install.txt
echo "-------"  | tee -a log-install.txt
echo "OpenSSH  : 22, 444"  | tee -a log-install.txt
echo "Dropbear : 80, 553"  | tee -a log-install.txt
echo "SSL      : 143"  | tee -a log-install.txt
echo "Squid3   : 8000, 8080 (limit to IP SSH)"  | tee -a log-install.txt
echo "OpenVPN  : TCP 1194 (client config : http://$MYIP:81/client.ovpn)"  | tee -a log-install.txt
echo "badvpn   : badvpn-udpgw port 7300"  | tee -a log-install.txt
echo "nginx    : 81"  | tee -a log-install.txt
echo ""  | tee -a log-install.txt
echo "Commands"  | tee -a log-install.txt
echo "------"  | tee -a log-install.txt
echo "menu       (Show Commands)"  | tee -a log-install.txt
echo "add        (Create User Account)"  | tee -a log-install.txt
echo "trial      (Create Trial Account)"  | tee -a log-install.txt
echo "remove     (Remove User Account)"  | tee -a log-install.txt
echo "check      (Check User Login)"  | tee -a log-install.txt
echo "member     (Check Member)"  | tee -a log-install.txt
echo "banner     (Configure Server Message)"  | tee -a log-install.txt
echo "restart    (Restart Service Dropbear, Webmin,"  | tee -a log-install.txt
echo "            Squid3, Openvpn and SSH)"  | tee -a log-install.txt
echo "reboot     (Reboot VPS)"  | tee -a log-install.txt
echo "speedtest  (Speedtest VPS)"  | tee -a log-install.txt
echo "info       (System Information)"  | tee -a log-install.txt
echo "about      (Debian AutoScript VPS Info)"  | tee -a log-install.txt
echo ""  | tee -a log-install.txt
echo "Other Features"  | tee -a log-install.txt
echo "----------"  | tee -a log-install.txt
echo "DDoS Deflate   : Anti-DDOS"  | tee -a log-install.txt
echo "Webmin         : http://$MYIP:10000/"  | tee -a log-install.txt
echo "Timezone       : Asia/Manila (GMT +7)"  | tee -a log-install.txt
echo "IPv6           : [off]"  | tee -a log-install.txt
echo "----------"  | tee -a log-install.txt
echo ""  | tee -a log-install.txt
echo "Installation Logs --> /root/log-install.txt"  | tee -a log-install.txt
echo ""  | tee -a log-install.txt
echo "VPS Auto Reboot at 12 AM"  | tee -a log-install.txt
echo ""  | tee -a log-install.txt
echo "==========================================="  | tee -a log-install.txt
cd
