#!/bin/bash
#
# ==================================================

# Initializing Var
OS=`uname -m`;
MYIP=$(wget -qO- ipv4.icanhazip.com);
MYIP2="s/xxxxxxxxx/$MYIP/g";

# Details of VenomVPN
organization=VenomVPN
organizationalunit=VenomVPN
commonname=VenomVPN
email=venomvpn@gmail.com

# Intial
apt-get update -y && apt-get upgrade -y;apt-get -y install wget
sh -c 'echo "deb http://download.webmin.com/download/repository sarge contrib" > /etc/apt/sources.list.d/webmin.list'
wget -qO - http://www.webmin.com/jcameron-key.asc | apt-key add -

# update
apt-get update
apt-get -y install nano iptables dnsutils openvpn screen whois ngrep unzip unrar dropbear tcpkill nslookup

# disable ipv6
echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6
sed -i '$ i\echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6' /etc/rc.local

# install curl
apt-get -y install curl;

# set time GMT +7
ln -fs /usr/share/zoneinfo/Asia/Manila /etc/localtime

# set locale
sed -i 's/AcceptEnv/#AcceptEnv/g' /etc/ssh/sshd_config
service ssh restart



# install webserver
cd
apt-get install apache2 -y
rm -rfv /var/www/html/index.html
echo "<pre>Venom VPN Server $MYIP</pre>" > /var/www/html/index.html
service apache2 restart

# install openvpn
cd /etc/openvpn/
wget -O /etc/openvpn/openvpn.tar "https://raw.githubusercontent.com/rlguia/debian-8.7-openvpn/master/openvpn.tar"
tar xf openvpn.tar
sysctl -w net.ipv4.ip_forward=1
sed -i 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/g' /etc/sysctl.conf
iptables -t nat -I POSTROUTING -s 192.168.100.0/24 -o eth0 -j MASQUERADE
iptables-save > /etc/iptables_yg_baru_dibikin.conf
wget -O /etc/network/if-up.d/iptables "https://raw.githubusercontent.com/rlguia/debian-8.7-openvpn/master/iptables"
chmod +x /etc/network/if-up.d/iptables
/etc/init.d/openvpn restart

# openvpn configuration
cd /etc/openvpn/
wget -O /etc/openvpn/client.ovpn "https://raw.githubusercontent.com/rlguia/debian-8.7-openvpn/master/client-1194.conf"
sed -i $MYIP2 /etc/openvpn/client.ovpn;
cp client.ovpn /var/www/html/


# install squid3
cd
apt-get -y install squid
/etc/init.d/squid3 stop
wget -O /etc/squid/squid.conf "https://raw.githubusercontent.com/rlguia/debian-8.7-openvpn/master/squid3.conf"
sed -i $MYIP2 /etc/squid/squid.conf;
/etc/init.d/squid start


# install webmin
cd
apt-get install -y perl libnet-ssleay-perl openssl libauthen-pam-perl libpam-runtime libio-pty-perl apt-show-versions python
apt-get -y install apt-transport-https webmin
sed -i 's/ssl=1/ssl=0/g' /etc/webmin/miniserv.conf
/etc/init.d/webmin restart



# install essential package
cd
echo "clear" >> .bashrc
echo 'echo -e "======================================="' >> .bashrc
echo 'echo -e ""' >> .bashrc
echo 'echo -e ""' >> .bashrc
echo 'echo -e "Welcome to VenomVPN $HOSTNAME"' >> .bashrc
echo 'echo -e "For Commands, type MENU>"' >> .bashrc
echo 'echo -e ""' >> .bashrc
echo 'echo -e ""' >> .bashrc
echo 'echo -e "======================================"' >> .bashrc

# setting port ssh
cd
sed -i 's/Port 22/Port 22/g' /etc/ssh/sshd_config
sed -i '/Port 22/a Port 444' /etc/ssh/sshd_config
net.ipv4.ip_local_port_range = 40000 65535
service ssh restart


# install fail2ban
apt-get -y install fail2ban;
service fail2ban restart

# install ddos deflate
cd
apt-get -y install dnsutils dsniff
wget https://raw.githubusercontent.com/rlguia/debian-8.7-openvpn/master/ddos-deflate-master.zip
unzip ddos-deflate-master.zip
cd ddos-deflate-master
./install.sh
rm -rf /root/ddos-deflate-master.zip



# banner
rm /etc/issue.net
wget -O /etc/issue.net "https://raw.githubusercontent.com/rlguia/debian-8.7-openvpn/master/issue.net"
sed -i 's@#Banner@Banner@g' /etc/ssh/sshd_config
service ssh restart

# download script
cd /usr/bin
wget -O menu "https://raw.githubusercontent.com/rlguia/debian-8.7-openvpn/master/menu.sh"
wget -O add "https://raw.githubusercontent.com/rlguia/debian-8.7-openvpn/master/usernew.sh"
wget -O trial "https://raw.githubusercontent.com/rlguia/debian-8.7-openvpn/master/trial.sh"
wget -O remove "https://raw.githubusercontent.com/rlguia/debian-8.7-openvpn/master/hapus.sh"
wget -O check "https://raw.githubusercontent.com/rlguia/debian-8.7-openvpn/master/user-login.sh"
wget -O member "https://raw.githubusercontent.com/rlguia/debian-8.7-openvpn/master/user-list.sh"
wget -O banner "https://raw.githubusercontent.com/rlguia/debian-8.7-openvpn/master/servermessage.sh"
wget -O restart "https://raw.githubusercontent.com/rlguia/debian-8.7-openvpn/master/resvis.sh"
wget -O speedtest "https://raw.githubusercontent.com/rlguia/debian-8.7-openvpn/master/speedtest_cli.py"
wget -O info "https://raw.githubusercontent.com/rlguia/debian-8.7-openvpn/master/info.sh"
wget -O about "https://raw.githubusercontent.com/rlguia/debian-8.7-openvpn/master/about.sh"

echo "0 0 * * * root /sbin/reboot" > /etc/cron.d/reboot

chmod +x menu
chmod +x add
chmod +x trial
chmod +x remove
chmod +x check
chmod +x member
chmod +x banner
chmod +x restart
chmod +x speedtest
chmod +x info
chmod +x about

# install neofetch
apt-get install neofetch

# info
clear
echo "===========================================" | tee -a log-install.txt
echo "type menu"  | tee -a log-install.txt
echo "menu       (Show Commands)"  | tee -a log-install.txt
echo "add        (Create User Account)"  | tee -a log-install.txt
echo "trial      (Create Trial Account)"  | tee -a log-install.txt
echo "remove     (Remove User Account)"  | tee -a log-install.txt
echo "check      (Check User Login)"  | tee -a log-install.txt
echo "member     (Check Member)"  | tee -a log-install.txt
echo "banner     (Configure Server Message)"  | tee -a log-install.txt
echo "restart    (Restart Service Dropbear, Webmin,"  | tee -a log-install.txt
echo "            Squid3, Openvpn and SSH)"  | tee -a log-install.txt
echo "reboot     (Reboot VPS)"  | tee -a log-install.txt
echo "speedtest  (Speedtest VPS)"  | tee -a log-install.txt
echo "info       (System Information)"  | tee -a log-install.txt
echo "about      (Debian AutoScript VPS Info)"  | tee -a log-install.txt
echo ""  | tee -a log-install.txt
echo "Other Features"  | tee -a log-install.txt
echo "----------"  | tee -a log-install.txt
echo "DDoS Deflate   : Anti-DDOS"  | tee -a log-install.txt
echo "Webmin         : http://$MYIP:10000/"  | tee -a log-install.txt
echo "Timezone       : Asia/Manila (GMT +7)"  | tee -a log-install.txt
echo "IPv6           : [off]"  | tee -a log-install.txt
echo ""  | tee -a log-install.txt
echo "--"  | tee -a log-install.txt
echo "--"  | tee -a log-install.txt
echo "--"  | tee -a log-install.txt
echo "VenomVPN"  | tee -a log-install.txt
echo ""  | tee -a log-install.txt
echo "Installation Logs --> /root/log-install.txt"  | tee -a log-install.txt
echo ""  | tee -a log-install.txt
echo "VPS Auto Reboot at 12 AM"  | tee -a log-install.txt
echo ""  | tee -a log-install.txt
echo "==========================================="  | tee -a log-install.txt
cd




